name: Check upstream filter rule types

on:
  schedule:
    - cron: "7 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_filter_rules:
    runs-on: ubuntu-latest

    env:
      PRE_COMMIT_HOME: '/tmp/pre-commit'
      # For gh cli in generate_filterrules.py
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt
          pip install pre-commit

      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.PRE_COMMIT_HOME }}
          key: ${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Generate filter rules
        run: |
          scripts/generate_filterrules.py --output DataModel/Sources/DataModel/FilterRuleType.swift
          pre-commit run swift-format --files DataModel/Sources/DataModel/FilterRuleType.swift || true

      - run: git diff

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: 'chore: Update Filter Rule types'
          commit-message: 'chore: Update Filter Rule types'
          branch: filter-rule-type-update
          delete-branch: true
          body: "Automated update of Filter Rule types."
          base: main
          add-paths: DataModel/Sources/DataModel/FilterRuleType.swift
